### Get all platforms
GET http://acme.com/api/c/platforms
Accept: application/json

### Get all commands for a platform
GET http://acme.com/api/c/platforms/1005/commands
Accept: application/json

### Get a command for a platform
GET http://acme.com/api/c/platforms/1005/commands/3
Accept: application/json

### Create a command for a platform
POST http://acme.com/api/c/platforms/1005/commands
Content-Type: application/json

{
  "HowTo": "How to do something",
  "CommandLine": "dotnet run"
}