### Get all platforms
GET http://acme.com/api/platforms
Accept: application/json

###

### Get platform by ID
GET http://acme.com/api/platforms/1
Accept: application/json

###

# ### Create new platform
POST http://acme.com/api/platforms
Content-Type: application/json

{
  "name": "Terr",
  "publisher": "Terraform",
  "cost": "Free"
}