### Get all platforms
GET http://acme.com/api/platforms
Accept: application/json

###

# ### Create new platform
# POST http://localhost:31151/api/platforms
# Content-Type: application/json

# {
#   "name": "Docker",
#   "publisher": "Docker",
#   "cost": "Free"
# }